app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('api/products/', include('products.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/products/api/urls.py
from django.urls import path
from . import views

app_name = "products-api"

urlpatterns = [
    # path('list/', views.product_list_view, name="list"),
    # path('create/', views.product_create_view, name="create"),
    # path('detail/<id>/', views.product_detail_view, name="detail"),
    # path('update/<id>/', views.product_update_view, name="update"),
    # path('delete/<id>/', views.product_delete_view, name="delete"),

    path('list/', views.ProductListView.as_view(), name='list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('detail/<id>/', views.ProductDetailView.as_view(), name='detail'),
    path('update/<id>/', views.ProductUpdateView.as_view(), name='update'),
    path('delete/<id>/', views.ProductDeleteView.as_view(), name='delete'),
]

app/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('detail/<id>/', views.product_detail_view, name='detail'),
    path('list/', views.product_list_view, name='list'),
    path('product-wish/', views.product_wish_view, name='product-wish'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('basket/', views.basket_list_view, name='basket'),
    path('add-basket/', views.add_basket_view, name='add-basket'),
    path('remove-basket/', views.remove_basket_view, name='remove-basket'),
]

app/products/models.py
from django.db import models
from services.mixins import DateMixin
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from services.uploader import Uploader

User = get_user_model()

# Create your models here.


from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Category(MPTTModel, DateMixin):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self) -> str:
        return self.name


class Product(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = RichTextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    wishlist = models.ManyToManyField(User, blank=True, related_name='product_wishlist')

    def __str__(self) -> str:
        return self.name



class ProductImage(DateMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=Uploader.upload_image_to_product)

    def __str__(self) -> str:
        return self.product.name


class Basket(DateMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.email} --> {self.user.fullname}"

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Basket'
        verbose_name_plural = 'Basket'

app/products/api/views.py
from rest_framework.response import Response
from rest_framework import generics
from products.models import Product
from .serializers import ProductListSerializer, ProductCreateSerializer
from django.db.models import F, FloatField
from django.db.models.functions import Coalesce
from rest_framework import status
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from .paginations import CustomPagination
from .permissions import IsOwnerOrReadOnly
from .filters import ProductFilter
from django_filters.rest_framework.backends import DjangoFilterBackend


class ProductListView(generics.ListAPIView):

    pagination_class = CustomPagination
    permission_classes = (IsAuthenticatedOrReadOnly, )
    filter_backends = (DjangoFilterBackend, )
    filterset_class = ProductFilter

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user).annotate(
            discount=Coalesce('discount_price', 0, output_field=FloatField()),
            total_price=F("price")-F('discount')
        )

    def get_serializer_class(self):
        return ProductListSerializer

class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.annotate(
        discount=Coalesce('discount_price', 0, output_field=FloatField()),
        total_price=F("price") - F('discount')
    ).all()

    def get_serializer_class(self):
        return ProductListSerializer

    def get_object(self):
        return self.queryset.get(id=int(self.kwargs.get("id")))

    lookup_field = "id"


class ProductCreateView(generics.CreateAPIView):
    serializer_class = ProductCreateSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class ProductUpdateView(generics.UpdateAPIView):

    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)
    queryset = Product.objects.annotate(
        discount=Coalesce('discount_price', 0, output_field=FloatField()),
        total_price=F("price") - F('discount')
    ).all()
    serializer_class = ProductListSerializer
    lookup_field = "id"


class ProductDeleteView(generics.DestroyAPIView):
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)
    queryset = Product.objects.annotate(
        discount=Coalesce('discount_price', 0, output_field=FloatField()),
        total_price=F("price") - F('discount')
    ).all()
    serializer_class = ProductListSerializer
    lookup_field = "id"

app/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Basket
from django.db.models import F, FloatField, Sum
from django.db.models.functions import Coalesce
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.


def index_view(request):

    categories = Category.objects.filter(parent__isnull=True)
    products = Product.objects.annotate(
        discount = Coalesce('discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price = F('price') - F('discount')
    ).annotate(
        percentage = (1-F('total_price')/F('price'))*100
    ).order_by("-created_at")

    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'products/index.html', context)

def product_detail_view(request, id):
    products = Product.objects.annotate(
        discount = Coalesce('discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price = F('price') - F('discount')
    ).annotate(
        percentage = (1-F('total_price')/F('price'))*100
    ).all()

    product = products.get(id=id)
    related_products = products.filter(category = product.category).exclude(id=product.id)

    context = {
        'product': product,
        'related_products': related_products, 
    }

    return render(request, 'products/detail.html', context)

@login_required(login_url='/login/')
def product_list_view(request):

    products = Product.objects.annotate(
        discount=Coalesce('discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price=F('price') - F('discount')
    ).annotate(
        percentage=(1 - F('total_price') / F('price')) * 100
    ).order_by("-created_at")
    categories = Category.objects.filter(parent__isnull=True)

    filter_dict = {}

    category = request.GET.get('category', None)
    if category:
        products = products.filter(
            category__in = Category.objects.get(id=int(category)).get_descendants(include_self=True)
        )
        filter_dict['category_id'] = int(category)

    min_price = request.GET.get('min_price', None)
    max_price = request.GET.get('max_price', None)

    if min_price:
        products = products.filter(total_price__gte=min_price)
        filter_dict["min_price"] = min_price
    if max_price:
        products = products.filter(total_price__lte=max_price)
        filter_dict["max_price"] = max_price

    order = request.GET.get('order', None)
    if order:
        filter_dict["order"] = 'latest'
        if order == 'name':
            products = products.order_by('name')
            filter_dict["order"] = order
        elif order == 'price':
            products = products.order_by('-total_price')
            filter_dict["order"] = order

    namecontain = request.GET.get('namecontain', None)
    if namecontain:
        filter_dict['namecontain'] = namecontain
        products = products.filter(name__icontains = namecontain)

    paginator = Paginator(products, 8)
    page = request.GET.get("page", 1)
    product_list = paginator.get_page(page)


    context = {
        'categories': categories,
        'products': product_list,
        'paginator': paginator,
        'filter_dict': filter_dict,
    }

    return render(request, 'products/list.html', context)

def product_wish_view(request):
    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    data = {}

    if request.user in product.wishlist.all():
        product.wishlist.remove(request.user)
        data['success'] = False
    else:
        product.wishlist.add(request.user)
        data['success'] = True

    return JsonResponse(data)

@login_required(login_url='/login/')
def wishlist_view(request):
    products = Product.objects.filter(wishlist__in = [request.user]).annotate(
        discount = Coalesce('discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price = F('price') - F('discount')
    )
    context = {
        "products": products
    }

    return render(request, 'wishlist/list.html', context)

@login_required(login_url='/login/')
def basket_list_view(request):
    baskets = Basket.objects.filter(user=request.user).annotate(
        discount = Coalesce('product__discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price = F('product__price') - F('discount')
    ).annotate(
        subtotal = F('total_price')*F("quantity")
    )
    total_price = baskets.aggregate(total=Coalesce(Sum("subtotal"), 0, output_field=FloatField()))['total']

    context = {
        "baskets": baskets,
        "total_price": total_price
    }
    return render(request, 'basket/list.html', context)


def add_basket_view(request):
    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    data = {}
    value = request.POST.get('value', None)
    basket_obj, created = Basket.objects.annotate(
        discount=Coalesce('product__discount_price', 0, output_field=FloatField())
    ).annotate(
        total_price=F('product__price') - F('discount')
    ).get_or_create(
        product=product, user=request.user, defaults={'quantity': 1}
    )

    if not value:
        if not created:
            basket_obj.quantity += 1
            basket_obj.save()
    else:
        basket_obj.quantity = int(value)
        basket_obj.save()
        data["subtotal"] = basket_obj.quantity * basket_obj.total_price
        baskets = Basket.objects.filter(user=request.user).annotate(
        discount = Coalesce('product__discount_price', 0, output_field=FloatField())
        ).annotate(
            total_price = F('product__price') - F('discount')
        ).annotate(
            subtotal = F('total_price') * F("quantity")
        )
        data["total"] = baskets.aggregate(total=Coalesce(Sum("subtotal"), 0, output_field=FloatField()))['total']




    return JsonResponse(data)


def remove_basket_view(request):
    product_id = request.POST.get('product_id')

    if product_id:
        removed_basket = Basket.objects.get(product__id=product_id, user=request.user)
        removed_basket.delete()
    return JsonResponse({})

app/templates/products/index.html
{% extends 'base.html' %}
{% load static %}
{% load change_value_format %}

{% block body %}

    <main class="main-wrapper">
        <!-- Start Categorie Area  -->
        <div class="axil-categorie-area pt--30 bg-color-white">
            <div class="container">
                <div class="categrie-product-activation-2 categorie-product-two slick-layout-wrapper--15">
                    {% for category in categories %}
                    <div class="slick-single-layout slick-slide">
                        <div class="categrie-product-2">
                            <a href="{% url 'products:list' %}?category={{category.id}}">
                                <img class="img-fluid" src="{% static '' %}assets/images/product/categories/furni-1.png" alt="product categorie">
                                <h6 class="cat-title">{{category.name}}</h6>
                            </a>
                        </div>
                        <!-- End .categrie-product -->
                    </div>
                    {% endfor %}
                    <!-- End .slick-single-layout -->

                </div>
            </div>
        </div>
        <!-- End Categorie Area  -->

        <!-- Start Slider Area -->
        <div class="axil-main-slider-area main-slider-style-5">
            <div class="container">
                <div class="slider-box-wrap">
                    <div class="slider-activation-two axil-slick-dots">
                        <div class="single-slide slick-slide">
                            <div class="main-slider-content">
                                <span class="subtitle"><i class="fas fa-fire"></i> Hot Deal In This Week</span>
                                <h1 class="title">Neon Stylish Sofa Chair</h1>
                                <div class="shop-btn">
                                    <a href="shop.html" class="axil-btn btn-bg-white"><i class="fal fa-shopping-cart"></i> Shop Now</a>
                                </div>
                            </div>
                            <div class="main-slider-thumb">
                                <img src="{% static '' %}assets/images/product/product-47.png" alt="Product">
                            </div>
                        </div>
                        <div class="single-slide slick-slide">
                            <div class="main-slider-content">
                                <span class="subtitle"><i class="fas fa-fire"></i> Hot Deal In This Week</span>
                                <h1 class="title">Sofa Chair with Lamp</h1>
                                <div class="shop-btn">
                                    <a href="shop.html" class="axil-btn btn-bg-white"><i class="fal fa-shopping-cart"></i> Shop Now</a>
                                </div>
                            </div>
                            <div class="main-slider-thumb">
                                <img src="{% static '' %}assets/images/product/product-48.png" alt="Product">
                            </div>
                        </div>
                        <div class="single-slide slick-slide">
                            <div class="main-slider-content">
                                <span class="subtitle"><i class="fas fa-fire"></i> Hot Deal In This Week</span>
                                <h1 class="title">Neon Stylish Sofa Chair</h1>
                                <div class="shop-btn">
                                    <a href="shop.html" class="axil-btn btn-bg-white"><i class="fal fa-shopping-cart"></i> Shop Now</a>
                                </div>
                            </div>
                            <div class="main-slider-thumb">
                                <img src="{% static '' %}assets/images/product/product-47.png" alt="Product">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Slider Area -->



        <!-- Start Expolre Product Area  -->
        <div class="axil-product-area bg-color-white axil-section-gap pb--0">
            <div class="container">
                <div class="product-area pb--80">
                    <div class="section-title-wrapper">
                        <span class="title-highlighter highlighter-primary"> <i class="far fa-shopping-basket"></i> Our Products</span>
                        <h2 class="title">Explore our Products</h2>
                    </div>
                    <div class="explore-product-activation slick-layout-wrapper slick-layout-wrapper--15 axil-slick-arrow arrow-top-slide">
                        <div class="slick-single-layout">
                            {% csrf_token %}
                            <div class="row row--15">

                                {% for product in products|slice:8 %}

                                <div class="col-xl-3 col-lg-4 col-sm-6 col-12 mb--30">
                                    <div class="axil-product product-style-one">
                                        <div class="thumbnail">
                                            <a href="{% url 'products:detail' product.id %}">
                                                <img data-sal="zoom-out" data-sal-delay="100" data-sal-duration="1500" src="{{product.productimage_set.first.image.url}}" alt="{{product.name}}">
                                            </a>
                                            {% if product.percentage %}
                                            <div class="label-block label-right">
                                                <div class="product-badget">{{product.percentage|formatize}}%</div>
                                            </div>
                                            {% endif %}
                                            <div class="product-hover-action">
                                                <ul class="cart-action">
                                                    <li class="quickview"><a href="#" data-bs-toggle="modal" data-bs-target="#quick-view-modal"><i class="far fa-eye"></i></a></li>
                                                    <li class="select-option"><a href="cart.html">Add to Cart</a></li>
                                                    <li class="wishlist"><a onclick="wishProduct({{product.id}})"><i class="far fa-heart" {% if request.user in product.wishlist.all %} style="color: red" {% endif %} id='product-heart-{{product.id}}'></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product-content">
                                            <div class="inner">
                                                <h5 class="title"><a href="{% url 'products:detail' product.id %}">{{product.name}}</a></h5>
                                                <div class="product-price-variant">
                                                    <span class="price current-price">{{product.total_price|formatize}} AZN</span>
                                                    {% if product.discount %}
                                                    <span class="price old-price">{{product.price|formatize}} AZN</span>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Product  -->

                                {% endfor %}

                            </div>
                        </div>
                        <!-- End .slick-single-layout -->
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-center mt--20 mt_sm--0">
                            <a href="{% url 'products:list' %}" class="axil-btn btn-bg-lighter btn-load-more">View All Products</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Expolre Product Area  -->



    </main>

{% block js %}
    <script>
        const wishlist_url = "{% url 'products:product-wish' %}"

        function wishProduct(id){

            var myHeaders = new Headers();
            myHeaders.append(
                "X-CSRFToken",
                document.querySelector("[name=csrfmiddlewaretoken]").value
            );

            var formData = new FormData();

            formData.append("product_id", id);

            var requestOptions = {
                method: "POST",
                headers: myHeaders,
                body: formData,
                redirect: "follow",
            };

            response = fetch(wishlist_url, requestOptions).then(function (response) {
                if (response.ok) {
                    response.json().then((data) => {
                        if(data.success){
                            $('#product-heart-'+id).css('color', 'red')
                        }
                        else{
                            $('#product-heart-'+id).css('color', 'black')
                        }
                    });
                }
            });
        }
    </script>
{% endblock %}


{% endblock %}