app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('api/products/', include('products.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('detail/<id>/', views.product_detail_view, name='detail'),
    path('list/', views.product_list_view, name='list'),
    path('product-wish/', views.product_wish_view, name='product-wish'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('basket/', views.basket_list_view, name='basket'),
    path('add-basket/', views.add_basket_view, name='add-basket'),
    path('remove-basket/', views.remove_basket_view, name='remove-basket'),
]

app/templates/basket/list.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <main class="main-wrapper">

        <!-- Start Cart Area  -->
        <div class="axil-product-cart-area axil-section-gap">
            <div class="container">
                <div class="axil-product-cart-wrap">
                    <div class="product-table-heading">
                        <h4 class="title">Your Cart</h4>
                        <a href="#" class="cart-clear">Clear Shoping Cart</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table axil-product-table axil-cart-table mb--40">
                            <thead>
                                <tr>
                                    <th scope="col" class="product-remove"></th>
                                    <th scope="col" class="product-thumbnail">Product</th>
                                    <th scope="col" class="product-title"></th>
                                    <th scope="col" class="product-price">Price</th>
                                    <th scope="col" class="product-quantity">Quantity</th>
                                    <th scope="col" class="product-subtotal">Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for basket in baskets %}
                                <tr id="basketDiv-{{basket.product.id}}">
                                    <td class="product-remove"><a onclick="removeBasket('{{basket.product.id}}')" class="remove-wishlist"><i class="fal fa-times"></i></a></td>
                                    <td class="product-thumbnail"><a href="single-product-3.html"><img src="{{basket.product.productimage_set.first.image.url}}" alt="Digital Product"></a></td>
                                    <td class="product-title"><a href="single-product-3.html">{{basket.product.name}}</a></td>
                                    <td class="product-price" data-title="Price"><span class="currency-symbol">$</span>{{basket.total_price}}</td>
                                    <td class="product-quantity" data-title="Qty">
                                        <div class="pro-qty">
                                            <input type="number" class="quantity-input" value="{{basket.quantity}}" id="product-qty-input-{{basket.product.id}}"
                                                   data-product-id="{{basket.product.id}}"
                                                   onchange="updateToCart('{{basket.product.id}}', '#product-qty-input-')"
                                            onkeyup="updateToCart('{{basket.product.id}}', '#product-qty-input-')">
                                        </div>
                                    </td>
                                    <td class="product-subtotal" data-title="Subtotal"><span class="currency-symbol">$</span>
                                        <span id="product-subtotal-{{basket.product.id}}">{{basket.subtotal}}</span>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="cart-update-btn-area">
                        <div class="input-group product-cupon">
                            <input placeholder="Enter coupon code" type="text">
                            <div class="product-cupon-btn">
                                <button type="submit" class="axil-btn btn-outline">Apply</button>
                            </div>
                        </div>
                        <div class="update-btn">
                            <a href="#" class="axil-btn btn-outline">Update Cart</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-5 col-lg-7 offset-xl-7 offset-lg-5">
                            <div class="axil-order-summery mt--80">
                                <h5 class="title mb--20">Order Summary</h5>
                                <div class="summery-table-wrap">
                                    <table class="table summery-table mb--30">
                                        <tbody>
<!--                                            <tr class="order-subtotal">-->
<!--                                                <td>Subtotal</td>-->
<!--                                                <td>$117.00</td>-->
<!--                                            </tr>-->
<!--                                            <tr class="order-shipping">-->
<!--                                                <td>Shipping</td>-->
<!--                                                <td>-->
<!--                                                    <div class="input-group">-->
<!--                                                        <input type="radio" id="radio1" name="shipping" checked>-->
<!--                                                        <label for="radio1">Free Shippping</label>-->
<!--                                                    </div>-->
<!--                                                    <div class="input-group">-->
<!--                                                        <input type="radio" id="radio2" name="shipping">-->
<!--                                                        <label for="radio2">Local: $35.00</label>-->
<!--                                                    </div>-->
<!--                                                    <div class="input-group">-->
<!--                                                        <input type="radio" id="radio3" name="shipping">-->
<!--                                                        <label for="radio3">Flat rate: $12.00</label>-->
<!--                                                    </div>-->
<!--                                                </td>-->
<!--                                            </tr>-->
<!--                                            <tr class="order-tax">-->
<!--                                                <td>State Tax</td>-->
<!--                                                <td>$8.00</td>-->
<!--                                            </tr>-->
                                            <tr class="order-total">
                                                <td>Total</td>
                                                <td class="order-total-amount">$ <span id="total-price">{{total_price}}</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <a href="checkout.html" class="axil-btn btn-bg-primary checkout-btn">Process to Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Cart Area  -->
        {% csrf_token %}

    </main>


    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static '' %}assets/images/icons/service1.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Fast &amp; Secure Delivery</h6>
                            <p>Tell about your service.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static '' %}assets/images/icons/service2.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Money Back Guarantee</h6>
                            <p>Within 10 days.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static '' %}assets/images/icons/service3.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">24 Hour Return Policy</h6>
                            <p>No question ask.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static '' %}assets/images/icons/service4.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Pro Quality Support</h6>
                            <p>24/7 Live support.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block js %}
<script>

        const basket_url = "{% url 'products:add-basket' %}"

        function updateToCart(id, input_id){

            var value = $(input_id+id).val()

            var myHeaders = new Headers();
            myHeaders.append(
                "X-CSRFToken",
                document.querySelector("[name=csrfmiddlewaretoken]").value
            );

            var formData = new FormData();

            formData.append("product_id", id);
            formData.append("value", value);

            var requestOptions = {
                method: "POST",
                headers: myHeaders,
                body: formData,
                redirect: "follow",
            };

            response = fetch(basket_url, requestOptions).then(function (response) {
                if (response.ok) {
                    response.json().then((data) => {
                        $("#product-subtotal-"+id).html(data.subtotal)
                        $("#total-price").html(data.total)
                    });
                }
            });

        }
        const basket_remove_url = "{% url 'products:remove-basket' %}"

        function removeBasket(id){

                var myHeaders = new Headers();
                myHeaders.append(
                    "X-CSRFToken",
                    document.querySelector("[name=csrfmiddlewaretoken]").value
                );

                var formData = new FormData();

                formData.append("product_id", id);

                var requestOptions = {
                    method: "POST",
                    headers: myHeaders,
                    body: formData,
                    redirect: "follow",
                };

                response = fetch(basket_remove_url, requestOptions).then(function (response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            $("#basketDiv-"+id).remove()
                        });
                    }
                });
            }





</script>
{% endblock %}