app/accounts/api/urls.py
from django.urls import path
from . import views

app_name = "accounts-api"


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("activate/<slug>/", views.ActivationView.as_view(), name="activate"),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset-password'),
    path('reset-password-check/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(), name='reset-password-check'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password')
]

app/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('activate-account/<slug>/', views.activate_account_view, name='activate-account'),
    path('change-password/', views.change_password_view, name='change-password'),
    path('reset-password/', views.reset_passsword_view, name='reset-password'),
    path('reset-password-check/<uuid64>/<token>/', views.reset_password_check_view, name='reset-password-check'),
    path('reset-password-complete/<uuid64>/', views.reset_password_complete_view, name='reset-password-complete'),
]

app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('api/products/', include('products.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()

class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'class-control'})

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        user = authenticate(email=email, password=password)

        if not user:
            raise forms.ValidationError('Email or password is wrong')

        if not user.is_active:
            raise forms.ValidationError('Your account is not active')

        return self.cleaned_data

class RegisterForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput, required=True)
    password_confirm = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ('email', 'fullname', 'password', 'password_confirm')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'class-control'})

    def clean(self):

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This username already exists')
        
        if password != password_confirm:
            raise forms.ValidationError('Passwords do not match')
        
        return self.cleaned_data

class ResetPasswordForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', )

    def clean(self):
        email = self.cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("This user does not exist")

        return self.cleaned_data

class ResetPasswordCompleteForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(), label='New password')
    password_confirm = forms.CharField(widget=forms.PasswordInput(), label='New password confirm')

    def clean(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password != password_confirm:
            raise forms.ValidationError('Passwords do not match')

        return self.cleaned_data

class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','fullname','password1','password2')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email','fullname','password', 'is_active', 'is_superuser')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

app/accounts/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from .serializers import (
    LoginSerializer, RegisterSerializer, ActivationSerializer, ResetPasswordSerializer, ResetPasswordConfirmSerializer,
    ChangePasswordSerializer
)
from accounts.models import MyUser as User
from django.contrib.auth import authenticate, get_user_model
from django.core.mail import send_mail
from rest_framework import status
from django.shortcuts import reverse
from django.conf import settings
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _
from rest_framework.permissions import IsAuthenticated


class LoginView(generics.CreateAPIView):
    serializer_class = LoginSerializer
    queryset = User.objects.all()

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        # email = serializer.validated_data.get("email")
        # user = User.objects.get(email=email)
        #
        # token = RefreshToken.for_user(user)
        #
        # data = {
        #     **serializer.data,
        #     "refresh": str(token),
        #     "access": str(token.access_token)
        # }

        return Response(serializer.data)


class RegisterView(generics.CreateAPIView):
    serializer_class = RegisterSerializer
    queryset = User.objects.all()

    # def post(self, request, *args, **kwargs):
    #     serializer = self.serializer_class(data=request.data)
    #     serializer.is_valid(raise_exception=True)
    #     user = serializer.save(is_active=True)
    #
    #     return Response(serializer.data, status=201)


class ActivationView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = ActivationSerializer
    lookup_field = 'slug'

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(
            data=request.data, context={"user": self.get_object()}
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)


class ResetPasswordView(generics.GenericAPIView):
    serializer_class = ResetPasswordSerializer

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        email = serializer.validated_data.get('email')
        user = User.objects.get(email=email)
        token = PasswordResetTokenGenerator().make_token(user)
        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))

        reset_link = request.build_absolute_uri(reverse(
            "accounts-api:reset-password-check",
            kwargs={'uidb64': uidb64, 'token': token},
        ))

        send_mail(
            "Password Reset",
            f"Please click the link below\n{reset_link}",
            settings.EMAIL_HOST_USER,
            [email]
        )

        return Response(
            {'message': 'Password reset link has been sent to your email.'},
            status=status.HTTP_200_OK
        )


class ResetPasswordConfirmView(generics.GenericAPIView):
    serializer_class = ResetPasswordConfirmSerializer

    def post(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and PasswordResetTokenGenerator().check_token(user=user, token=token):
            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            password = serializer.validated_data.get('password')
            user.password = make_password(password)
            user.save()
            return Response({'message': 'Password has been reset successfully.'}, status=status.HTTP_200_OK)
        else:
            return Response({'error': _('Invalid reset link.')}, status=status.HTTP_400_BAD_REQUEST)


class ChangePasswordView(generics.UpdateAPIView):
    # permission_classes = (IsAuthenticated, )
    serializer_class = ChangePasswordSerializer

    def update(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = authenticate(
            email=serializer.validated_data['email'],
            password=serializer.validated_data['old_password']
        )

        if user is not None:
            user.set_password(serializer.validated_data['new_password'])
            user.save()
            return Response({'detail': 'Password changed successfully.'}, status=status.HTTP_200_OK)

        return Response({'detail': 'Old password is incorrect.'}, status=status.HTTP_400_BAD_REQUEST)

app/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .forms import LoginForm, RegisterForm, ResetPasswordForm, ResetPasswordCompleteForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from services.generator import Generator
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .decorators import not_authorized_user, check_activation_code_time
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.encoding import smart_str, force_str, smart_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode


User = get_user_model()

def login_view(request):

    form = LoginForm()
    next_url = request.GET.get('next', None)

    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            user = authenticate(email=email, password=password)
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect('/')

        else:
            print(form.errors) 

    context = {
        'form': form
    }

    return render(request, 'accounts/login.html', context)

@not_authorized_user
def register_view(request):

    form = RegisterForm()

    # if request.user.is_authenticated:
    #     return redirect('/')

    if request.method == 'POST':
        form = RegisterForm(request.POST or None)

        if form.is_valid():
            new_user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            new_user.set_password(password)
            new_user.is_active = False
            new_user.activation_code = Generator.create_activation_code(size=6, model_=User)
            new_user.activation_code_expires_at = timezone.now() + timezone.timedelta(minutes=15)
            new_user.save()

            # mail sending
            send_mail(
                "eTrade - Activation Code",
                f"Your Activation code is: {new_user.activation_code}",
                settings.EMAIL_HOST_USER,
                [new_user.email]
            )

            return redirect('accounts:activate-account', slug=new_user.slug)

    context = {
        'form': form
    }

    return render(request, 'accounts/register.html', context)

def logout_view(request):

    logout(request)
    return redirect('/')

@check_activation_code_time
def activate_account_view(request, slug):
    user = get_object_or_404(User, slug=slug)

    if request.method == 'POST':
        code = request.POST.get('code', None)

        if code == user.activation_code:
            user.is_active = True
            user.activation_code = None
            user.activation_code_expires_at = None
            user.save()

            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Activation code is incorrect!')

    context = {

    }

    return render(request, 'accounts/activate-account.html', context)

@login_required(login_url='/login/')
def change_password_view(request):
    form = PasswordChangeForm(user=request.user)

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST or None, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)

            return redirect('/')

    context = {
        "form": form,
    }

    return render(request, 'accounts/change-password.html', context)

def reset_passsword_view(request):
    form = ResetPasswordForm

    if request.method == "POST":
        form = ResetPasswordForm(request.POST or None)

        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = User.objects.get(email=email)

            # mail process
            uuid64 = urlsafe_base64_encode(smart_bytes(user.id))
            token = PasswordResetTokenGenerator().make_token(user)

            link = request.build_absolute_uri(reverse(
                "accounts:reset-password-check",
                kwargs={'uuid64': uuid64, 'token': token},

            ))
            # sending mail
            send_mail(
                "Password Reset",
                f"Please click the link below\n{link}",
                settings.EMAIL_HOST_USER,
                [email]
            )


            return redirect('accounts:login')

    context = {
        'form': form
    }

    return render(request, 'accounts/reset-password.html', context)


def reset_password_check_view(request, uuid64, token):
    id = smart_str(urlsafe_base64_decode(uuid64))
    user = User.objects.get(id=id)

    if not PasswordResetTokenGenerator().check_token(user=user, token=token):
        messages.error(request, 'Token is wrong.')
        return redirect('accounts:login')

    return redirect('accounts:reset-password-complete', uuid64=uuid64)

def reset_password_complete_view(request, uuid64):
    form = ResetPasswordCompleteForm()

    id = smart_str(urlsafe_base64_decode(uuid64))
    user = User.objects.get(id=id)

    if request.method == 'POST':
        form = ResetPasswordCompleteForm(request.POST or None)

        if form.is_valid():
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()

            return redirect('/login/')
    context = {
        'form': form
    }

    return render(request, 'accounts/reset-password-complete.html', context)

app/templates/accounts/activate-account.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from new.axilthemes.com/demo/template/etrade/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Mar 2023 15:09:57 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>eTrade || Sign Up</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static '' %}assets/images/favicon.png">

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/flaticon/flaticon.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/slick.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/jquery-ui.min.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/sal.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/magnific-popup.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/base.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/style.min.css">

</head>


<body>
    <div class="axil-signin-area">

        <!-- Start Header -->
        <div class="signin-header">
            <div class="row align-items-center">
                <div class="col-sm-4">
                    <a href="index-2.html" class="site-logo"><img src="{% static '' %}assets/images/logo/logo.png" alt="logo"></a>
                </div>
                <div class="col-sm-8">
                    <div class="singin-header-btn">
                        <p>already a member?</p>
                        <a href="{% url 'accounts:login' %}" class="axil-btn btn-bg-secondary sign-up-btn">Sign In</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header -->

        <div class="row">
            <div class="col-xl-4 col-lg-6">
                <div class="axil-signin-banner bg_image bg_image--9">
                    <h3 class="title">We Offer the Best Products</h3>
                </div>
            </div>
            <div class="col-lg-6 offset-xl-2">
                <div class="axil-signin-form-wrap">
                    <div class="axil-signin-form">
                        <h3 class="title">Sign Up to eTrade.</h3>
                        <p class="b2 mb--55">Enter your detail below</p>
                        <p>{% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% endif %}</p>
                        <form class="singin-form" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Enter activation code:</label>
                                <!-- <input type="email" class="form-control" name="email" value="annie@example.com"> -->
                                <input type="text" maxlength="6" id="code" name="code" class="form-control">
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between">
                                <button type="submit" class="axil-btn btn-bg-primary submit-btn">Sign Up</button>
                                <a href="forgot-password.html" class="forgot-btn">Forget password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static '' %}assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="{% static '' %}assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="{% static '' %}assets/js/vendor/popper.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/bootstrap.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/slick.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/js.cookie.js"></script>
    <!-- <script src="{% static '' %}assets/js/vendor/jquery.style.switcher.js"></script> -->
    <script src="{% static '' %}assets/js/vendor/jquery-ui.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/jquery.countdown.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/sal.js"></script>
    <script src="{% static '' %}assets/js/vendor/jquery.magnific-popup.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/imagesloaded.pkgd.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/isotope.pkgd.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/counterup.js"></script>
    <script src="{% static '' %}assets/js/vendor/waypoints.min.js"></script>

    <!-- Main JS -->
    <script src="{% static '' %}assets/js/main.js"></script>

</body>


<!-- Mirrored from new.axilthemes.com/demo/template/etrade/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Mar 2023 15:09:57 GMT -->
</html>

app/templates/accounts/login.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from new.axilthemes.com/demo/template/etrade/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Mar 2023 15:09:57 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>eTrade || Sign In</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static '' %}assets/images/favicon.png">

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/flaticon/flaticon.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/slick.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/jquery-ui.min.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/sal.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/magnific-popup.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/vendor/base.css">
    <link rel="stylesheet" href="{% static '' %}assets/css/style.min.css">

</head>


<body>
    <div class="axil-signin-area">

        <!-- Start Header -->
        <div class="signin-header">
            <div class="row align-items-center">
                <div class="col-sm-4">
                    <a href="index-2.html" class="site-logo"><img src="{% static '' %}assets/images/logo/logo.png" alt="logo"></a>
                </div>
                <div class="col-sm-8">
                    <div class="singin-header-btn">
                        <p>Not a member?</p>
                        <a href="{% url 'accounts:register' %}" class="axil-btn btn-bg-secondary sign-up-btn">Sign Up Now</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header -->

        <div class="row">
            <div class="col-xl-4 col-lg-6">
                <div class="axil-signin-banner bg_image bg_image--9">
                    <h3 class="title">We Offer the Best Products</h3>
                </div>
            </div>
            <div class="col-lg-6 offset-xl-2">
                <div class="axil-signin-form-wrap">
                    <div class="axil-signin-form">
                        <h3 class="title">Sign in to eTrade.</h3>
                        {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}
                        {% endif %}

                        {% if form.errors %}
                        <div class="error-message mb-4">
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error|escape }}
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error|escape }}
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <p class="b2 mb--55">Enter your detail below</p>
                        <form class="singin-form" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>{{form.email.label}}</label>
                                <!-- <input type="email" class="form-control" name="email" value="annie@example.com"> -->
                                {{form.email}}
                            </div>
                            <div class="form-group">
                                <label>{{form.password.label}}</label>
                                <!-- <input type="password" class="form-control" name="password" value="123456789"> -->
                                {{form.password}}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between">
                                <button type="submit" class="axil-btn btn-bg-primary submit-btn">Sign In</button>
                                <a href="forgot-password.html" class="forgot-btn">Forget password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static '' %}assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="{% static '' %}assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="{% static '' %}assets/js/vendor/popper.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/bootstrap.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/slick.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/js.cookie.js"></script>
    <!-- <script src="{% static '' %}assets/js/vendor/jquery.style.switcher.js"></script> -->
    <script src="{% static '' %}assets/js/vendor/jquery-ui.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/jquery.countdown.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/sal.js"></script>
    <script src="{% static '' %}assets/js/vendor/jquery.magnific-popup.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/imagesloaded.pkgd.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/isotope.pkgd.min.js"></script>
    <script src="{% static '' %}assets/js/vendor/counterup.js"></script>
    <script src="{% static '' %}assets/js/vendor/waypoints.min.js"></script>

    <!-- Main JS -->
    <script src="{% static '' %}assets/js/main.js"></script>

</body>


<!-- Mirrored from new.axilthemes.com/demo/template/etrade/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Mar 2023 15:09:57 GMT -->
</html>